### ISSUE TITLE
Error running compile64.bat

### ISSUE THREAD

**Issue by crimsoncore** [slaeryan/AQUARMOURY#2]
I get this error when trying to compile (Visual Studio Community 2019 installed), any ideas?

C:\Code\AQUARMOURY\Shellycoat>compile64.bat
Microsoft (R) Macro Assembler (x64) Version 14.00.24245.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: Src\\syscalls64.asm
dllmain.cpp
c:\Code\AQUARMOURY\Shellycoat\Src\Syscalls.h(108): error C3861: '__readgsqword': identifier not found
Could Not Find c:\Code\AQUARMOURY\Shellycoat\dllmain.obj

**Comment by slaeryan** [comment]
I believe that you are using the x86 developer command prompt which doesn't support this intrinsic.
Switching to the x64 version of MSVC compiler/linker should fix this problem.
